# netlify.toml (at repo root)
[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# 1 rule to cover every function
[[redirects]]
from = "/api/*"
to   = "/.netlify/functions/:splat"
status = 200

# (put your SPA fallback LAST so it doesn't eat /api/*)
[[redirects]]
from = "/*"
to   = "/index.html"
status = 200